# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-11 22:41
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
import django.contrib.postgres.fields
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Metadata',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('key', models.CharField(max_length=256)),
                ('acquired', models.DateTimeField(db_index=True, null=True)),
                ('published', models.DateTimeField(db_index=True, null=True)),
                ('processed', models.DateTimeField(db_index=True, null=True)),
                ('bytes', models.BigIntegerField(blank=True, null=True)),
                ('pixels', models.BigIntegerField(blank=True, null=True)),
                ('cloud_fraction', models.FloatField(db_index=True, null=True)),
                ('fill_fraction', models.FloatField(db_index=True, null=True)),
                ('geom', django.contrib.gis.db.models.fields.GeometryField(null=True, srid=4326)),
                ('data', django.contrib.postgres.fields.jsonb.JSONField()),
                ('groups', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=80), size=None)),
            ],
            options={
                'db_table': 'metadata',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True)),
                ('groups', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=80), size=None)),
            ],
            options={
                'db_table': 'product',
            },
        ),
        migrations.AddField(
            model_name='metadata',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spoons.Product'),
        ),
        migrations.AlterUniqueTogether(
            name='metadata',
            unique_together=set([('key', 'product')]),
        ),
    ]
